# Generated by Django 4.2.5 on 2023-09-25 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to='employee.employee', verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_quantity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Order Quantity'),
        ),
        migrations.AddField(
            model_name='order',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='order',
            name='inventory',
            field=models.ManyToManyField(to='inventory.inventory', verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Amount'),
        ),
    ]
