# Generated by Django 4.2.5 on 2023-09-14 07:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
                ('ammount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ammount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('method', models.CharField(blank=True, choices=[('card', 'Card'), ('link', 'Link'), ('bank_transfer', 'Bank Transfer'), ('check_po', 'Check/ Postal Order')], max_length=25, null=True, verbose_name='Payment Method')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('authorized', 'Authorized'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('on_hold', 'On Hold')], max_length=25, null=True, verbose_name='Payment Status')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subject')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('review', 'Review'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], max_length=25, null=True, verbose_name='Status')),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=25, null=True, verbose_name='Priority')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ticket Type')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('tag', models.TextField(blank=True, null=True, verbose_name='Tags')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['-created_on'],
            },
        ),
    ]
