# Generated by Django 4.2.5 on 2023-09-26 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(verbose_name=datetime.timedelta(seconds=300)),
        ),
    ]
