# Generated by Django 4.2.5 on 2023-09-15 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(error_messages={'unique': 'A user with that mobile phone number already exists.'}, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile phone number must be in the format: 07XX XXX XXX', regex='^(07\\d{8})$')], verbose_name='Mobile Phone: '),
        ),
    ]
