# Generated by Django 4.2.4 on 2023-08-31 14:27

import crm_apps.core.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', crm_apps.core.manager.UserManager()),
            ],
        ),
    ]
