# Generated by Django 4.2.5 on 2023-09-13 04:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={"ordering": ("name",)},
        ),
    ]
