# Generated by Django 4.2.5 on 2023-09-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-created_on'], 'verbose_name': 'Inventory'},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventory',
            name='instock_quantity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instock Quantity'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='type',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
