# Generated by Django 4.2.5 on 2023-09-26 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_options_remove_inventory_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-created_on'], 'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
    ]
