# Generated by Django 4.2.5 on 2023-09-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inventory_manufacturer_remove_inventory_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='use',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
