# Generated by Django 4.2.5 on 2023-09-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_inventory_amount_remove_inventory_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='instock_quantity',
            field=models.CharField(max_length=50, verbose_name='Instock Quantity'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Product Name'),
        ),
    ]
