# Generated by Django 4.2.5 on 2023-09-18 04:06

import apps.core.manager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('team_manager', 'Team Manager'), ('team_lead', 'Team Lead'), ('agent', 'Agent'), ('customer_care', 'Customer Care'), ('escalator', 'Escalator'), ('verifier', 'Verifier')], max_length=50, verbose_name='Role')),
                ('reporting_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportees', to='employee.employee', verbose_name='Reporting to')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': ['-created_on'],
            },
            bases=('core.customuser',),
            managers=[
                ('user', apps.core.manager.UserManager()),
                ('objects', apps.core.manager.UserManager()),
            ],
        ),
    ]
