<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-09-04 10:12
=======
# Generated by Django 4.2.4 on 2023-09-02 06:29
>>>>>>> development

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD
    dependencies = [
        ("employee", "0001_initial"),
=======

    dependencies = [
        ('employee', '0001_initial'),
>>>>>>> development
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="employee",
            name="position",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Position"
            ),
=======
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Position'),
>>>>>>> development
        ),
    ]
