# Generated by Django 4.2.5 on 2023-09-18 04:06

import apps.core.manager
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
                ('address1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Town/City')),
                ('postal_code', models.CharField(blank=True, max_length=150, null=True, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, max_length=150, null=True, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('landline_phone', models.CharField(error_messages={'unique': 'A user with that landline phone number already exists.'}, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Landline phone number must be in the format: (XX) XXXX XXXX or XX XXXX XXXX', regex='^\\((0[2-9]|[2-9]\\d)\\)\\s?\\d{4}\\s?\\d{4}$|^(0[2-9]|[2-9]\\d)\\s?\\d{8}$')], verbose_name='Landline Phone: ')),
                ('dnc', models.BooleanField(default=False, verbose_name='Do Not Call')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_address', to='customer.address')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['-created_on'],
            },
            bases=('core.customuser',),
            managers=[
                ('user', apps.core.manager.UserManager()),
                ('objects', apps.core.manager.UserManager()),
            ],
        ),
    ]
