# Generated by Django 4.2.4 on 2023-09-01 10:07

import apps.core.manager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('source', models.CharField(blank=True, choices=[('outbound', 'Outbound'), ('inbound', 'Inbound'), ('website', 'Website'), ('email', 'Email')], max_length=255, null=True, verbose_name='Source of Lead')),
                ('dnc', models.BooleanField(default=False, verbose_name='Do Not Call')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['-created_on'],
            },
            bases=('core.customuser',),
            managers=[
                ('user', apps.core.manager.UserManager()),
                ('objects', apps.core.manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
                ('appt_no', models.CharField(blank=True, max_length=150, null=True, verbose_name='Appartment Number')),
                ('street_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Number')),
                ('street_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Street Name')),
                ('suburb', models.CharField(blank=True, max_length=150, null=True, verbose_name='Suburb')),
                ('state', models.CharField(blank=True, max_length=150, null=True, verbose_name='State')),
                ('postal_code', models.CharField(blank=True, max_length=150, null=True, verbose_name='Postal Code')),
                ('lat', models.CharField(blank=True, max_length=150, null=True, verbose_name='Latitude')),
                ('long', models.CharField(blank=True, max_length=150, null=True, verbose_name='Longitude')),
                ('country', models.CharField(default='Australia', max_length=150, verbose_name='Country')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_address', to='customer.customer')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ['-created_on'],
            },
        ),
    ]
