# Generated by Django 4.2.5 on 2023-09-15 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='landline_phone',
            field=models.CharField(error_messages={'unique': 'A user with that landline phone number already exists.'}, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Landline phone number must be in the format: (XX) XXXX XXXX or XX XXXX XXXX', regex='^\\((0[2-9]|[2-9]\\d)\\)\\s?\\d{4}\\s?\\d{4}$|^(0[2-9]|[2-9]\\d)\\s?\\d{8}$')], verbose_name='Landline Phone: '),
        ),
    ]
