# Generated by Django 4.2.4 on 2023-09-05 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_address_customer_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='source',
        ),
        migrations.AddField(
            model_name='customer',
            name='landline_phone',
            field=models.CharField(default=3285698745, error_messages={'unique': 'A user with that landline phone number already exists.'}, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Landline phone number must be in the format: (XX) XXXX XXXX or XX XXXX XXXX', regex='^\\((?:0[2-9]|[2-9]\\d)\\)\\s?\\d{4}\\s?\\d{4}$|^(?:0[2-9]|[2-9]\\d)\\s?\\d{8}$')], verbose_name='Landline Phone: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
    ]
